title: Build differently with APEXaaaaa
description: Your central point to manage, monitor and harden security for APIs
  within the Whole-of-Government.sdcsdcsd

section1:
    - title: The platform for secure digital services
    - subTitle: APEX makes it simple to publish, maintain, monitor and secure your APIs.