backend:
    name: git-gateway
    repo: rav3/test-cms
local_backend: true
show_preview_links: true

media_folder: "assets/images"
collections:
    - name: "Home Page"
      label: "Home Page"
      description: "Upcoming tours and their availability"
      files:
        - label: "Hero Banner"
          name: "hero-banner"
          file: "_data/site.yml"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "string"}

        - label: "Section 1"
          name: "section-one"
          file: "_data/site.yml"
          fields:
            - {label: "Title", name: "section1.title", widget: "string"}
            - {label: "Sub Title", name: "section1.subTitle", widget: "string"}
