backend:
    name: git-gateway
    repo: APEX2/apex-cms
local_backend: true

media_folder: "assets/images"
collections:
    - name: "Home Page"
      label: "Home Page"
      description: "Upcoming tours and their availability"
      files:
        - label: "Hero Banner"
          name: "Hero Banner"
          file: "_data/site.yml"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Description", name: "description", widget: "string"}
