backend:
    # name: git-gateway
    # repo: rav3/test-cms
    name: test-repo
local_backend: true
logo_url: https://placehold.it/50x50

media_folder: assets/images
collections:
  - label: Home Page
    name: homePage
    description: Upcoming tours and their availability
    files:
      - label: Content
        name: content
        file: _data/home/content.yml
        widget : object
        fields:
          - label: Hero Banner
            name: heroBanner
            widget: object
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
          - label: Section 1
            name: section1
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - label: list
                name: list
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Description, name: description, widget: string}
  - label: "Post"
    name: "post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      # - {label: Image, name: img, widget: image}

