backend:
    name: git-gateway
    repo: rav3/test-cms

media_folder: "assets/images"
collections:
    - name: "tourInfo"
      label: "Tour Info"
      description: "Upcoming tours and their availability"
      files:
        - label: "tour"
          name: "Tour"
          file: "_data/site.yml"
          fields:
            - label: "Tour List"
              name: "tourList"
              widget: "list"
              fields:
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Description", name: "description", widget: "string"}
